import unittest
from server import app  # Assuming 'app' is the Flask app instance in server.py

# This intial unit test generated by ChatGPT prompt: Tech me how to test return_review_data in a flask context
# NOTE: You can run this with python3 -m unittest servertest.py
# Ask Connor for any clarification
class ReviewTestCase(unittest.TestCase):
    def setUp(self):
        self.app = app.test_client()  # Create a test client for the app

    def test_get_reviews(self):
        # Simulate a GET request to the route
        response = self.app.get('/reviews/get/1337')

        # Assert that the response is successful (HTTP 200)
        self.assertEqual(response.status_code, 200)
        
        # Optionally, check if the returned JSON is correct
        data = response.get_json()
        print(data)
        self.assertTrue(len(data) > 0)  # Make sure there's data in the response

    def test_get_user_reviews(self):    
        response = self.app.get('/reviews/get/user/Jameson')

        self.assertEqual(response.status_code, 200)
        data = response.get_json()
        print(data)
        self.assertTrue(len(data) > 0)


if __name__ == '__main__':
    unittest.main()
